export default {
  // Title
  logHeader: 'Welcome!',
  login: 'Login',
  regHeader: 'Register Now!',
  register: 'Sign up',
  placeholderUserNameTitle: 'Username',
  placeholderEmailTitle: 'Email',
  placeholderPasswordTitle: 'Password',
  placeholderEmail: 'Your email...',
  placeholderPassword: 'Your password...',
  placeholderUsername: 'Fullname...',
  greet: 'Hello',
  greet2: 'What you want to cook today?',
  searchBarPlaceHolder: 'Search',
  langBoxTitle: 'Choose languages',
  imgCoverText: 'Add Cover Image',
  dropDownLabel: 'Select Category',
  recipeTitle: 'Recipes Name',
  placeholderRecipeText: 'Enter your recipe name here',
  prepTimeTitle: 'Preparation Time',
  placeholderPreTime: 'Enter cooking time',
  addIngBtnText: 'Add ingredients to your recipes',
  descTitle: 'Description',
  placeholderDescText: 'Enter Description',
  recDoneBtn: 'Done',
  addPhoto: 'Add a photo',
  fromCamera: 'Take a photo',
  fromGallery: 'Choose from gallery',
  cancle: 'Cancle',
  langTitle: 'Language',
  aboutTitle: 'About LetCook',
  logoutTitle: 'Logout',
  addIngText: 'Add ingredients',
  bioTitle: 'About',
  bioPlaceholder: 'Enter you About',
  updateBtn: 'Save',
  emptyCard: 'Empty Bookmark',
  placeholderPrepTime: 'Enter cooking time',

  // success
  regSuccess: 'Register Successful',
  logSuccess: 'Logged in Successful',
  rmvSuccess: 'Remove bookmark successful',
  createRecSuccess: 'Create Recipes Successful',
  updateRecSuccess: 'Update Recipes Successful',
  updateProSuccess: 'Update Profile Successful',
  rmvUrRec: 'Remove recipes successful',

  //error
  error: 'Something went wrong, please try again!',
  logError: 'Username and password did not match',
  validLogError: 'Please fill out the required fields.',
  duplicateEmailError: 'That email address is already in use!',
};
