export default {
  // Title
  logHeader: 'မင်္ဂလာပါ',
  login: 'အကောင့်၀င်ရန်',
  regHeader: 'အကောင့်သစ်ဖွင့်ပါ',
  register: 'အကောင့်သစ် ပြုလုပ်ရန်',
  placeholderUserNameTitle: 'နာမည်',
  placeholderEmailTitle: 'အီမေလ်',
  placeholderPasswordTitle: 'စကား၀ှက်',
  placeholderEmail: 'အီးမေလ်...',
  placeholderPassword: 'စကား၀ှက်...',
  placeholderUsername: 'နာမည်...',
  greet: 'မင်္ဂလာပါ',
  greet2: 'သင်ဒီနေ့ဘာချက်ခြင်ပါသလဲ',
  searchBarPlaceHolder: 'ရှာမည်',
  langBoxTitle: 'ဘာသာစကားရွှေးခြယ်ပါ',
  imgCoverText: 'ပုံရွှေးပါ',
  dropDownLabel: 'အမျိုးအစားရွှေးပါ',
  recipeTitle: 'ဟင်းလျာအမည်',
  placeholderRecipeText: 'ဟင်းလျာအမည်ထည့်ရန်',
  prepTimeTitle: 'ပြင်ဆင်ချိန်',
  placeholderPrepTime: 'ကြာချိန်ထည့်ရန်',
  addIngBtnText: 'ပါ၀င်စ္စည်းများထည့်ရန်',
  descTitle: 'ရှင်းလင်ချက်များ',
  placeholderDescText: 'ရှင်းလင်းချက်များထည့်ရန်',
  recDoneBtn: 'ထည့်သွင်းမည်',
  addPhoto: 'ပုံထည့်မည်',
  fromCamera: 'ကင်မရာမှယူရန်',
  fromGallery: 'ဖိုင်မှယူရန်',
  cancle: 'ဖျက်သိမ်မည်',
  langTitle: 'ဘာသာစကား',
  aboutTitle: 'LetCook အကြောင်း',
  logoutTitle: 'ထွက်မည်',
  addIngText: 'ပါ၀င်ပစ္စည်းထည့်သွင်းလိုက်ပါပြီ',
  bioTitle: 'ကိုယ်ရေးအကျဉ်း',
  bioPlaceholder: 'ကိုယ်ရေးအကျဉ်း...',
  updateBtn: 'သိမ်းမည်',
  emptyCard: 'မရှိသေးပါ',

  // success
  regSuccess: 'အကောင့်သစ်ဖွင့်ခြင်း အောင်မြင်ပါသည်',
  logSuccess: 'အကောင့်၀င်ရောက်ခြင်း အောင်မြင်ပါသည်',
  rmvSuccess: 'ဖျက်သိမ်းခြင်းအောင်မြင်ပါသည်',
  createRecSuccess: 'ဟင်းလျာဖန်တီးခြင်းအောင်မြင်ပါသည်',
  updateRecSuccess: 'ပြင်ဆင်ခြင်းအောင်မြင်ပါသည်',
  updateProSuccess: 'ပြင်ဆင်ခြင်းအောင်မြင်ပါသည်',
  rmvUrRec: 'ဖျက်သိမ်းခြင်းအောင်မြင်ပါသည်',

  // error
  error: 'တခုခုမှားယွင်းနေပါသည်',
  logError: 'အကောင့်(သို့)လျှို့ ၀ှက်နံပါတ် မှားယွင်းနေပါသည်',
  validLogError: 'လိုအပ်သောကွက်လပ်များကိုဖြည့်ပေးပါ',
  duplicateEmailError: 'အမည်မှာရှိပြီးသားဖြစ်ပါသည်တခြားအမည်ပြောင်းသုံးပေးပါ',
};
